#Last time graph made for EHBEA poster
pdf("img/rand.pdf",pointsize=21)
pdf("~/projects/PhD/doc/conferences/20170406_EHBEA/img/rand.pdf",pointsize=21)
par(mar=c(4,4,2,0))
hist(c(-1,rand$epsilon),ylim=c(0,100),xlim=c(0,1),breaks=50,xlab=expression(epsilon),main="")
dev.off()
library(scales)
pdf("~/projects/PhD/doc/conferences/20170406_EHBEA/img/trade.pdf",pointsize=21)
par(mar=c(4,4,2,0))
hist(c(-1,trade$epsilon),density=10,ylim=c(0,100),xlim=c(0,1),breaks=50,xlab=expression(epsilon),main="")
rect(-1,-1,.25,101,col=alpha("red",.2),border=F)
abline(v=.25,col="red")
text(.1,25,expression(epsilon < 0.25),col="red")
dev.off()
mean(trade$epsilon)
mean(rand$epsilon)
median(trade$epsilon)
