#!/bin/bash
#BSUB -J province 
#BSUB -oo province_proto.log 
#BSUB -eo province_proto.err 

##################################################
# Fill here with a number of cpus according to   #
# your needs.                                    #
# Keep in mind that one task is reserved for the #
# master if using the mpi engine.                #
##################################################

#BSUB -n NTASKS 
#BSUB -R"span[ptile=16]"

##################################################
# and set an appropiate wall_clock_limit         #
##################################################

#BSUB -W TIME

##################################################
# Here goes the path to the file where you have  #
# the list of tasks.                             #
##################################################

FILE=province_proto.task

##################################################
# Here goes the path to the place where the logs #
# will be written.                               #
# By default, if not set, it will use:           #
# ./greasy.log                                   #
# or                                             #
# ./greasy-<jobid>.log if inside lsf job         #
##################################################

# export GREASY_LOGFILE=greasy.log

##################################################
# If running this script interactively, please   #
# set the desired number of workers. The number  #
# of workers should not be higher than the       #
# available cpus.                                #
# If remote spawning is available, set up the    #
# comma-separated hostlist as well.              #
##################################################

#export GREASY_NWORKERS=1


#export GREASY_TASKS_PER_NODE=4
# export GREASY_NODELIST=node1,node2,node3

##################################################
# Run greasy!                                    #
##################################################

/apps/GREASY/latest/bin/greasy $FILE

